#! python3

#passwordlocker.py is an insecure password locker program by Drew Barton


passwords = {'email':'F7minlBDDuvMJuxESSKHFhTxFtjVB6',
             'blog':'VmALvQyKAxiVH5G8v01if1MLZF3sdt',
             'luggage':'12345'}

import sys, pyperclip
if len(sys.argv) < 2:
    print('Usage: python passwordlocker.py [account] - copy account password')
    sys.exit()

account = sys.argv[1]               #first command line arg is account name

if account in passwords:
    pyperclip.copy(passwords[account])
    print('password for ' + account + ' copied to clipboard.')
else:
    print('There is no account named ' + account)
